### ISSUE TITLE
possibility to modify http headers as well

### ISSUE THREAD

**Issue by ask2018** [JustOff/modify-http-response#7] opened 2021-05-18 16:04 UTC
Hi and first let me say thank you for this awesome addon. This is more like feature idea/request than actual bug. My idea is if it would be possible to also add possibility to modify or add any http header sent by browser to any page or domain. Similar way how we can modify and rewrite https responses from pages now. We would be able also modify any header send by browser back to the webpage.That would make this addon even more powerful in my opinion. Thank you for reply.

**Comment by JustOff** [comment] 2021-05-22 17:40
Duplicate of #5.

**Closed as completed by JustOff** 2021-05-22 17:40 UTC
Labels: duplicate

**Comment by ask2018** [comment] 2021-05-23 11:40
Sorry missed the previous issue number 5. But the user there is not asking about exactly the same as me. He just wants to modify all responses and that's really possible with the extension you mentioned there. What I want to achieve is modify header only for specific pages like it is possible with your extension for http response. And that is not possible with the other extension. But ok I will try to open issue for this function there.
