### ISSUE TITLE
Multiprocess issue

### ISSUE THREAD

**Issue by gdl-blue** [JustOff/modify-http-response#8] opened 2021-08-01 06:25 UTC
When e10s multiprocess mode is enabled in Serpent/Firefox 52/Centaury(`browser.tabs.remote.force-enable`) the extension does not work, it does not modify the response.

**Comment by JustOff** [comment] 2021-08-01 06:54
Duplicate of #6.

**Closed as completed by JustOff** 2021-08-01 06:54 UTC
Labels: duplicate
